### ISSUE TITLE
What is the release date of Steeltoe 2.0 version

### ISSUE THREAD

**Issue by VenkateshSrini** [SteeltoeOSS/Home#3]
Hi,

In spring one held in 2017, it was told that the Steel Toe 2.0 version rc will be released in December 2017. But I see that the latest NuGet version are still showing as 1.1.*. So could you please let us now what is the expected release date for Steel Toe version 2.0

**Comment by TimHess** [comment]
Hi @VenkateshSrini,
All of the 2.0 RC1 packages are available on nuget.org, and all of the samples have been updated to use them. It is important to note that some of the package names have changed (eg: the packages that show on nuget.org as 1.1.* being newest), so you'll want to take a peek at the samples as we're still working on updating the documentation.  If you're still not seeing the RC1 packages in Visual Studio, you may need to check the box to show prerelease packages.

**Comment by VenkateshSrini** [comment]
@TimHess ,
Could you please provide us with the list of package names that we need to use and their equivalent preceding version. That will be of immense help for us to correct our old reference.

**Comment by TimHess** [comment]
Ok... As you can see, it isn't exactly 1:1 with the update as packages are setup a little bit different now. I'll get more in depth as I update the docs, but this list should have all the packages in 1.1 and 2.0.
In general, a package ending in Base is probably consumed via another package, depending on how your application is setup (use *Core for aspnetcore apps, *Autofac for net461 apps that use Autofac)

_If you're using Steeltoe and are not using Microsoft DI or Autofac, please let us know (or optionally offer to contribute) so we can track where it makes sense to add functionality_

| Library | 1.1 Packages  | 2.0 Packages |
|---|---|---|
| CircuitBreaker | Steeltoe.CircuitBreaker.Hystrix<br>Steeltoe.CircuitBreaker.Hystrix.Core<br> Steeltoe.CircuitBreaker.Hystrix.MetricsEvents<br> Steeltoe.CircuitBreaker.Hystrix.MetricsStream | Steeltoe.CircuitBreaker.HystrixBase<br>Steeltoe.CircuitBreaker.HystrixCore<br>Steeltoe.CircuitBreaker.HystrixAutofac<br>Steeltoe.CircuitBreaker.Hystrix.MetricsEventsCore<br>Steeltoe.CircuitBreaker.Hystrix.MetricsStreamCore |
| Common | n/a | Steeltoe.Common<br>Steeltoe.Common.Net<br>Steeltoe.Common.Http<br>Steeltoe.Common.Autofac |
| Configuration | Steeltoe.Extensions.Configuration.CloudFoundry<br>Steeltoe.Extensions.Configuration.ConfigServer<br>Pivotal.Extensions.Configuration.ConfigServer |  Steeltoe.Extensions.Configuration.ConfigServerBase<br>Steeltoe.Extensions.Configuration.ConfigServerAutofac<br>Steeltoe.Extensions.Configuration.ConfigServerCore<br>Steeltoe.Extensions.Configuration.CloudFoundryBase<br>Steeltoe.Extensions.Configuration.CloudFoundryAutofac<br>Steeltoe.Extensions.Configuration.CloudFoundryCore<br>Pivotal.Extensions.Configuration.ConfigServerBase<br>Pivotal.Extensions.Configuration.ConfigServerAutofac<br>Pivotal.Extensions.Configuration.ConfigServerCore |
| Connectors | Steeltoe.CloudFoundry.Connector<br>Steeltoe.CloudFoundry.Connector.Hystrix<br>Steeltoe.CloudFoundry.Connector.MySql<br>Steeltoe.CloudFoundry.Connector.OAuth<br>Steeltoe.CloudFoundry.Connector.PostgreSql<br>Steeltoe.CloudFoundry.Connector.Rabbit<br>Steeltoe.CloudFoundry.Connector.Redis | Steeltoe.CloudFoundry.ConnectorBase<br>Steeltoe.CloudFoundry.ConnectorCore<br>Steeltoe.CloudFoundry.Connector.EF6Core<br>Steeltoe.CloudFoundry.Connector.EFCore |
| Discovery | Steeltoe.Discovery.Client<br>Steeltoe.Discovery.Eureka.Client<br>Pivotal.Discovery.Client | Steeltoe.Discovery.ClientAutofac<br>Steeltoe.Discovery.ClientCore<br>Steeltoe.Discovery.EurekaBase<br>Pivotal.Discovery.ClientCore<br>Pivotal.Discovery.ClientAutofac<br>Pivotal.Discovery.EurekaBase |
| Logging | Steeltoe.Extensions.Logging.CloudFoundry | Steeltoe.Extensions.Logging.DynamicLogger |
| Management | Steeltoe.Management.Endpoint<br>Steeltoe.Management.Endpoint.CloudFoundry<br>Steeltoe.Management.Endpoint.Health<br>Steeltoe.Management.Endpoint.Info<br>Steeltoe.Management.Endpoint.Loggers<br>Steeltoe.Management.Endpoint.Trace<br>Steeltoe.Management.CloudFoundry | Steeltoe.Management.EndpointBase<br>Steeltoe.Management.EndpointCore<br>Steeltoe.Management.CloudFoundryCore |
| Security |Steeltoe.Security.Authentication.CloudFoundry<br>Steeltoe.Security.DataProtection.Redis | Steeltoe.Security.Authentication.CloudFoundryCore<br>Steeltoe.Security.Authentication.CloudFoundryOwin<br>Steeltoe.Security.Authentication.CloudFoundryWcf<br>Steeltoe.Security.DataProtection.CredHubBase<br>Steeltoe.Security.DataProtection.CredHubCore<br>Steeltoe.Security.DataProtection.RedisCore|

**Comment by VenkateshSrini** [comment]
@TimHess ,

Thank you very much. This answer is worth the blog
